name: 'Parse Ref Semver'
description: 'Parse a github ref (usually a tag) and extract the semver version, optional package scope, and optional package name'
inputs:
  ref:
    description: 'The github ref to parse (e.g. refs/tags/v1.0.0, refs/tags/pkg@v1.2.3)'
    required: true
outputs:
  ref:
    description: The ref that was parsed
  matched:
    description: \"true\" if the ref matched the semver pattern, \"false\" otherwise
  scope:
    description: The package scope (if any) from the tag (e.g. @scope/package-name@v1.2.3 -> scope)
  name:
    description: The package name (if any) from the tag (e.g. @scope/package-name@v1.2.3 -> package-name)
  major:
    description: The major version from the tag (e.g. v1.2.3 -> 1)
  minor:
    description: The minor version from the tag (e.g. v1.2.3 -> 2)
  patch:
    description: The patch version from the tag (e.g. v1.2.3 -> 3)
  prerelease:
    description: The prerelease version from the tag (e.g. v1.2.3-alpha.1 -> alpha.1)
  build:
    description: The build metadata from the tag (e.g. v1.2.3+build.1 -> build.1)
runs:
  using: 'node20'
  main: 'dist/index.js'
