name: publish clide-js npm package

on:
  workflow_dispatch:
  # release:
  #   types: [published]

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/clide-js@v')
    name: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: install yarn
        run: npm i -g yarn

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: build
        run: yarn workspace clide-js build

      - name: copy root readme
        run: cp README.md packages/clide-js/

      - name: parse ref
        uses: ./.github/actions/parse-ref-semver
        id: parse
        with:
          ref: ${{ github.ref }}

      - name: publish next
        if: steps.parse.outputs.prerelease
        working-directory: packages/clide-js/
        run: npm publish --access public --tag next

      - name: publish latest
        if: steps.parse.outputs.prerelease == ''
        working-directory: packages/clide-js/
        run: npm publish --access public
