name: test clide-js

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/clide-js/**'
      - 'packages/tsconfig/**'
      - '.github/workflows/test-clide.yml'

concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: install Yarn
        run: npm i -g yarn

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: run tests
        run: yarn workspace clide-js test:ci
