name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/clide-js/**'
      - 'packages/clide-plugin-command-menu/**'
      - 'packages/tsconfig/**'

concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Clide Tests
        if: needs.detect-clide-changes.outputs.changed == 'true'
        run: yarn workspace clide-js test:ci

      - name: Run Command Menu Tests
        if: needs.detect-command-menu-changes.outputs.changed == 'true'
        run: yarn workspace clide-plugin-command-menu test:ci
