name: test parse ref semver

on:
  workflow_dispatch:

jobs:
  parse:
    uses: ./.github/workflows/parse-ref-semver.yml
    with:
      ref: refs/tags/hyperdrive-wasm@v1.2.3

  test:
    runs-on: ubuntu-latest
    needs: parse
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Print outputs
        run: |
          echo "package-scope=${{ needs.parse.outputs.package-scope }}"
          echo "package-name=${{ needs.parse.outputs.package-name }}"
          echo "major=${{ needs.parse.outputs.major }}"
          echo "minor=${{ needs.parse.outputs.minor }}"
          echo "patch=${{ needs.parse.outputs.patch }}"
          echo "prerelease=${{ needs.parse.outputs.prerelease }}"
          echo "build=${{ needs.parse.outputs.build }}"
