name: test clide-plugin-command-menu

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/clide-js/**'
      - 'packages/clide-plugin-command-menu/**'
      - 'packages/tsconfig/**'

concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: install yarn
        run: npm i -g yarn

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: run tests
        run: yarn workspace clide-plugin-command-menu test:ci
